#spring application config
spring:
  application:
    name: ticket_resell
  #datasource config
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  #jpa config
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
#server config
server:
  port: 8081
  servlet:
    context-path: /ticket_resell/api
